Implemented implementation
itmo-java-basics-2020/task-3-hashtable-classes-inner-classes-class-object-Leemurus pull request #1
Opened 2020-03-13 20:32 UTC by Leemurus

2020-03-22 15:41 UTC, AfanasievYuriy requested changes

2020-03-22 15:41 UTC, AfanasievYuriy commented on src/main/java/ru/itmo/java/HashTable.java
> +        return removeInIndex(getIndex(key));
тоже самое

2020-03-22 15:41 UTC, AfanasievYuriy commented on src/main/java/ru/itmo/java/HashTable.java
> +        return getValueUsingIndex(getIndex(key));
здесь тоже самое: почему реализацию getValueUsuingIndex сюда не поместить? Если тебе нужна эта функциональность внутри других методов класса - пользуешь этим паблик методом и все

2020-03-22 15:41 UTC, AfanasievYuriy commented on src/main/java/ru/itmo/java/HashTable.java
> +        return putInIndex(getIndex(key), key, value);
зачем столько приватных методов? optimizeTable, например, да (утилитарный метод как ни крути), но почему логику метода putInIndex не поместить сразу сюда, в метод put?

2020-03-22 15:41 UTC, AfanasievYuriy commented on src/main/java/ru/itmo/java/HashTable.java
> +    private int capacity, size;
поля класса принято помещать в самый верх класса

2020-03-22 15:54 UTC, AfanasievYuriy requested changes
Снизу вверх коменты читай
Я немного попутал порядок)

2020-03-22 16:27 UTC, AfanasievYuriy commented on src/main/java/ru/itmo/java/HashTable.java
> +    private int getHashIndex(Object object) {
приватные метоты в классе принято помещать после публичных

2020-03-23 01:34 UTC, AfanasievYuriy commented on src/main/java/ru/itmo/java/HashTable.java
> +            changeTableSize(capacity * 2);
я бы `changeTableSize` засунул бы сюда. Не вижу смысла в данном случае плодить 2 приватных метода

2020-03-23 17:51 UTC, Leemurus commented on src/main/java/ru/itmo/java/HashTable.java
> +        return getValueUsingIndex(getIndex(key));
В двух других согласен, но здесь немного другой момент, ведь в get я просто получаю объект ключ и для этого мне сначала нужно найти индекс его в массиве, а потом получить значение. А в методах где, я вставляю и я добавляю мне нужно получить значение по индексу. Поэтому это будет нецелесообразно в плане скорости.

2020-03-27 23:52 UTC, AfanasievYuriy commented on src/main/java/ru/itmo/java/HashTable.java
> +        return getValueUsingIndex(getIndex(key));
ладно, убедил

2020-03-27 23:52 UTC, AfanasievYuriy approved these changes

2020-03-27 23:53 UTC, AfanasievYuriy commented
А, это еще: не надо резолвить комментарии после того как ты их поправил - это задача ревьювера (я сам хочу резолвить, где мне кажется что все ок)

2024-12-11 19:42 UTC, closed without merging